pip install keyboard
pip install datetime
pip install getpass
pip install paramiko
pip install requests
pip install colorama
@echo off
echo.
echo ======================================================================================================
echo.
echo PIP installation finished! - Press any key to continue.
echo.
echo ======================================================================================================
echo.
pause
exit