: Go Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Go version from go.mod
        id: go-version
        run: |
          GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')
          echo "go-version=$GO_VERSION" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}

      - name: Build
        run: |
          GOOS=windows GOARCH=amd64 go build -o FyUTILS ./...

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-artifact@v3
        with:
          name: FyUTILS.exe
          path: FyUTILS.exe

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Release Notes
        id: release_notes
        run: |
          

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: FyUTILS ${{ github.ref_name }}
          body: ${{ env.release_body }}
          draft: false
          prerelease: false

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: FyUTILS.exe
          asset_name: FyUTILS.exe
          asset_content_type: application/vnd.microsoft.portable-executable